//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMusicSound.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public int pay_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> pakage_id { get; set; }
        public Nullable<System.DateTime> pay_datecreate { get; set; }
        public Nullable<System.DateTime> pay_dateexpiration { get; set; }
        public Nullable<decimal> pay_summoney { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual User User { get; set; }
    }
}
