//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMusicSound.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int profile_id { get; set; }
        public Nullable<System.DateTime> profile_birth { get; set; }
        public string profile_phone { get; set; }
        public string profile_name { get; set; }
        public string profile_lastname { get; set; }
        public string profile_note { get; set; }
        public string profile_favorite { get; set; }
        public Nullable<int> sex_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string profile_address { get; set; }
    
        public virtual Sex Sex { get; set; }
        public virtual User User { get; set; }
    }
}
